<a href="https://colab.research.google.com/github/AmeliaReginaa/PROJECT-AKHIR-DEEP-LEARNING-SISTEM-MULTIMEDIA/blob/main/Preprocesing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocesing

In [ ]:
# 1. IMPORT LIBRARY
import pandas as pd
import numpy as np
import re
import nltk
from nltk.tokenize import word_tokenize
# Install Sastrawi if not already installed
!pip install Sastrawi
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

nltk.download('punkt')

Requirement already satisfied: Sastrawi in /usr/local/lib/python3.12/dist-packages (1.0.1)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [ ]:
# 2. LOAD DATASET
# Load dataset
df_gojek = pd.read_csv('/content/gojek_reviews.csv')
df_grab = pd.read_csv('/content/grab_reviews.csv')

# Ambil kolom penting (sesuaikan kalau nama kolom beda)
df_gojek = df_gojek[['content','score',]]
df_grab = df_grab[['content','score']]

# Tambahkan penanda aplikasi
df_gojek['app'] = 'Gojek'
df_grab['app'] = 'Grab'

print("Jumlah data Gojek:", len(df_gojek))
print("Jumlah data Grab:", len(df_grab))

Jumlah data Gojek: 5000
Jumlah data Grab: 5000

In [ ]:
# Gabung Dataset
df = pd.concat([df_gojek, df_grab], ignore_index=True)

print("Total data gabungan:", len(df))
df.head()

Total data gabungan: 10000

                   content  score    app
0                   Mantap      5  Gojek
1  pesanan cepat di terima      5  Gojek
2          penyiksa driver      1  Gojek
3          mudah digunakan      5  Gojek
4                   mantap      5  Gojek

In [ ]:
# Gabung Dataset
df = pd.concat([df_gojek, df_grab], ignore_index=True)

print("Total data gabungan:", len(df))
df.head()

Total data gabungan: 10000

                   content  score    app
0                   Mantap      5  Gojek
1  pesanan cepat di terima      5  Gojek
2          penyiksa driver      1  Gojek
3          mudah digunakan      5  Gojek
4                   mantap      5  Gojek

In [ ]:
# 3. BUAT LABEL DARI RATING
def label_sentiment(score):
    if score >= 4:
        return "positif"
    elif score == 3:
        return "netral"
    else:
        return "negatif"

df['label'] = df['score'].apply(label_sentiment)

print(df['label'].value_counts())

label
positif    6561
negatif    3053
netral      386
Name: count, dtype: int64

In [ ]:
# 4. CLEANING TEXT
def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"#\w+", "", text)
    text = re.sub(r"[^a-zA-Z\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df['clean_review'] = df['content'].apply(clean_text)

In [ ]:
# 5. ENCODE LABEL
label_encoder = LabelEncoder()
df['encoded_label'] = label_encoder.fit_transform(df['label'])

print(dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))

{'negatif': np.int64(0), 'netral': np.int64(1), 'positif': np.int64(2)}

In [ ]:
# SAVE DATASET CLEAN
df_clean = df[['clean_review', 'label', 'encoded_label']]

df_clean.to_csv("combined_reviews_clean.csv", index=False)

print("Dataset bersih berhasil disimpan!")

Dataset bersih berhasil disimpan!